/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_idibon_ml_cld2_CLD2_DocumentMode */

#ifndef _Included_com_idibon_ml_cld2_CLD2_DocumentMode
#define _Included_com_idibon_ml_cld2_CLD2_DocumentMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
