/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_idibon_ml_cld2_CLD2 */

#ifndef _Included_com_idibon_ml_cld2_CLD2
#define _Included_com_idibon_ml_cld2_CLD2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_idibon_ml_cld2_CLD2
 * Method:    cld2_Detect
 * Signature: ([BZ)I
 */
JNIEXPORT jint JNICALL Java_com_idibon_ml_cld2_CLD2_cld2_1Detect
  (JNIEnv *, jclass, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
